name: Build & Test

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes main
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./Application/
    - name: Build
      run: dotnet build ./Application/ --no-restore
    - name: Test
      run: dotnet test ./Application/ --no-build --verbosity normal
